### ISSUE TITLE
Is the keyword missing a corresponding value?

### ISSUE THREAD

**Issue by xcandxc** [changwoonchoi/IBL-NeRF#11]
Hello,Line 223 in ibl_nerf_renderer.py (mask_img = gt_values["edit_intrinsic_mask"][:, 0]), what is the explanation for this line? Is there a value missing for "edit_intrinsic_mask"? And what is the usage of "gt_values"?

**Comment by changwoonchoi** [comment]
1. Explanation for gt_values["edit_intrinsic_mask"][:,0]
The code assumes that mask images for intrinsic component editing are gray RGB images. Since all values in R, G, and B channels are identical, we need only one of them. (in this code, we use values from the R channel.)
2. gt_values
parameter gt_values in 
https://github.com/changwoonchoi/IBL-NeRF/blob/8e099535bb61a48490dca97972830651bb0d2f2f/src/nerf_models/ibl_nerf_renderer.py#L153
are target information of corresponding pixels.
e.g. in
https://github.com/changwoonchoi/IBL-NeRF/blob/8e099535bb61a48490dca97972830651bb0d2f2f/src/train.py#L294
obtained from sample generator.
